# Travis script that uses miniconda in place of the system installed python
# versions.  Allows substantial flexability for choosing versions of
# required packages and is simpler to use to test up-to-date scientific Python
# stack
language: python

matrix:
  fast_finish: false
  include:
  - python: 2.7
    env:
    - PYTHON=2.6
    - NUMPY=1.6
    - SCIPY=0.11
    - CYTHON=0.20
    - PATSY=0.2.0
    - MATPLOTLIB=1.2
    - PANDAS=0.12
  - python: 2.7
    env:
    - PYTHON=2.7
    - NUMPY=1.7
    - SCIPY=0.12
    - CYTHON=0.20
    - PATSY=0.2
    - MATPLOTLIB=1.3
    - PANDAS=0.12
  - python: 2.7
    env:
    - PYTHON=3.3
    - NUMPY=1.8
    - SCIPY=0.13
    - CYTHON=0.20
    - PATSY=0.2
    - MATPLOTLIB=1.3
    - PANDAS=0.13

notifications:
  email:
    on_success: always

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  # Fix for headless TravisCI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Avoid noise from matplotlib
  - mkdir $HOME/.config
  - mkdir $HOME/.config/matplotlib
  - SRCDIR=$PWD
  - cp $SRCDIR/tools/matplotlibrc $HOME/.config/matplotlib/matplotlibrc
  # Location for older version of matplotlib
  - mkdir $HOME/.matplotlib
  - cp $SRCDIR/tools/matplotlibrc $HOME/.matplotlib/matplotlibrc

# Install packages
install:
  # mkl is installed due to bug in how conda handles the Python 2.6 environment
  - conda create --yes --quiet -n statsmodels-test python=$PYTHON numpy=$NUMPY scipy=$SCIPY patsy=$PATSY Cython=$CYTHON matplotlib=$MATPLOTLIB pandas=$PANDAS dateutil nose pip pyyaml setuptools mkl
  - source activate statsmodels-test
  - pip install coverage coveralls
  - python setup.py install

script:
  - SRCDIR=$PWD
  - python setup.py install
  - mkdir -p "${SRCDIR}/travis-test"; cd "${SRCDIR}/travis-test"
  # Show versions
  - python -c 'import statsmodels.api as sm; sm.show_versions();'
  # Compose a script to run testing with coverage
  - echo 'import statsmodels as sm; a=sm.test(); import sys; sys.exit((len(a.failures)+len(a.errors))>0)' > test.py
  - if [ ${PYTHON} == "2.7" ]; then coverage run --rcfile=${SRCDIR}/.travis_coveragerc test.py; else python test.py; fi

after_success:
  # Coverage only for 2.7
  - if [ ${PYTHON} == "2.7" ]; then coveralls --rcfile=${SRCDIR}/.travis_coveragerc; fi